### ISSUE TITLE
patel includes a tests package

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/pastel-feedstock#5]
The evil twin of https://github.com/conda-forge/tomlkit-feedstock/issues/24 , this ships a `tests` package which ends up in `site-packages`, which is (at least) a test-time dependency of poetry (conda-forge/poetry-feedstock#39). This causes `ClobberWarning`s:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pastel-0.2.0-py_0, defaults/linux-64::tomlkit-0.7.0-py37h89c1867_2
  path: 'lib/python3.7/site-packages/tests/conftest.py'
```

As this feedstock doesn't run those tests, the easiest thing to do is to remove the `tests` folder (and/or patch out the `setup.{py,cfg}` that requires them). PR akin to https://github.com/conda-forge/tomlkit-feedstock/issues/24 incoming!

**Comment by cbrueffer** [comment]
Fixed by https://github.com/conda-forge/pastel-feedstock/pull/6
